// OCRPNGDecoderTests.swift
//
// P6-C (Linux OCR): unit tests for `PNGDecoder` (this module's from-scratch
// PNG decoder built on `Inflate` — see `PNGDecoder.swift`'s doc comment).
//
// `fixturePNGBytes`/`fixtureExpectedRGBA` were generated by a Python script
// (`zlib.compress` + hand-applied PNG filters cycling through all 5 filter
// types — None/Sub/Up/Average/Paeth — across the image's 7 rows) whose
// filtered+compressed output became this fixture, and whose UN-filtered
// original pixel values became the expected RGBA array — i.e. this test
// verifies `PNGDecoder.decode` reproduces pixel data that was computed
// completely independently of this Swift implementation, exercising real
// DEFLATE decompression (dynamic Huffman, since `zlib.compress` almost never
// emits fixed-Huffman or stored blocks for non-trivial input) and all 5 PNG
// filter reconstructions in one fixture. This is the same technique used to
// validate `Inflate`/`PNGDecoder` during development — see this task's
// handoff notes for the full 5-fixture cross-check transcript (gradient,
// RGBA+alpha, grayscale, random noise, solid color, split-IDAT).
import Testing

@testable import ClipnestLinuxOCR

@Suite("PNGDecoder")
struct OCRPNGDecoderTests {

  // 9x7 RGBA, filters cycling None/Sub/Up/Average/Paeth by row, compressed
  // with zlib level 9 (produces dynamic-Huffman DEFLATE blocks).
  private static let fixturePNGBytes: [UInt8] = [
    137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 9, 0, 0, 0, 7, 8, 6, 0,
    0, 0, 218, 155, 103, 96, 0, 0, 0, 128, 73, 68, 65, 84, 120, 218, 99, 96, 103, 102, 56, 161,
    202, 44, 120, 216, 153, 89, 105, 95, 34, 179, 241, 206, 122, 102, 151, 45, 115, 153, 67, 215,
    239, 102, 78, 91, 117, 147, 185, 124, 233, 119, 230, 142, 5, 140, 236, 138, 130, 71, 229, 24,
    4, 127, 227, 195, 76, 12, 114, 130, 127, 9, 97, 102, 22, 59, 165, 56, 126, 126, 193, 63, 248,
    48, 11, 88, 53, 3, 1, 204, 62, 51, 116, 167, 234, 204, 180, 45, 206, 51, 203, 215, 39, 206,
    236, 88, 85, 63, 115, 230, 210, 185, 51, 87, 45, 216, 61, 115, 247, 236, 155, 51, 207, 76, 251,
    62, 243, 238, 68, 70, 246, 237, 105, 219, 8, 57, 28, 0, 246, 20, 86, 22, 69, 17, 240, 192, 0,
    0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130,
  ]
  private static let fixtureExpectedRGBA: [UInt8] = [
    7, 3, 0, 200, 37, 3, 17, 195, 67, 3, 34, 190, 97, 3, 51, 185, 127, 3, 68, 180, 157, 3, 85, 175,
    187, 3, 102, 170, 217, 3, 119, 165, 247, 3, 136, 160, 7, 33, 17, 197, 37, 33, 34, 192, 67, 33,
    51, 187, 97, 33, 68, 182, 127, 33, 85, 177, 157, 33, 102, 172, 187, 33, 119, 167, 217, 33, 136,
    162, 247, 33, 153, 157, 7, 63, 34, 194, 37, 63, 51, 189, 67, 63, 68, 184, 97, 63, 85, 179, 127,
    63, 102, 174, 157, 63, 119, 169, 187, 63, 136, 164, 217, 63, 153, 159, 247, 63, 170, 154, 7,
    93, 51, 191, 37, 93, 68, 186, 67, 93, 85, 181, 97, 93, 102, 176, 127, 93, 119, 171, 157, 93,
    136, 166, 187, 93, 153, 161, 217, 93, 170, 156, 247, 93, 187, 151, 7, 123, 68, 188, 37, 123,
    85, 183, 67, 123, 102, 178, 97, 123, 119, 173, 127, 123, 136, 168, 157, 123, 153, 163, 187,
    123, 170, 158, 217, 123, 187, 153, 247, 123, 204, 148, 7, 153, 85, 185, 37, 153, 102, 180, 67,
    153, 119, 175, 97, 153, 136, 170, 127, 153, 153, 165, 157, 153, 170, 160, 187, 153, 187, 155,
    217, 153, 204, 150, 247, 153, 221, 145, 7, 183, 102, 182, 37, 183, 119, 177, 67, 183, 136, 172,
    97, 183, 153, 167, 127, 183, 170, 162, 157, 183, 187, 157, 187, 183, 204, 152, 217, 183, 221,
    147, 247, 183, 238, 142,
  ]

  private static let fixtureUnsupportedBitDepthPNG: [UInt8] = [
    137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4, 16, 2, 0,
    0, 0, 118, 3, 213, 106, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130,
  ]
  private static let fixtureUnsupportedPaletteColorTypePNG: [UInt8] = [
    137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4, 8, 3, 0,
    0, 0, 158, 47, 110, 76, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130,
  ]
  private static let fixtureUnsupportedInterlacePNG: [UInt8] = [
    137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4, 8, 2, 0,
    0, 1, 81, 148, 57, 191, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130,
  ]

  @Test("Decodes a real RGBA PNG (all 5 filter types, dynamic Huffman) to pixel-exact RGBA8")
  func decodesRealPNGPixelExact() {
    let image = PNGDecoder.decode(Self.fixturePNGBytes)
    #expect(image?.width == 9)
    #expect(image?.height == 7)
    #expect(image?.pixels == Self.fixtureExpectedRGBA)
  }

  @Test("readHeader reads width/height/colorType without needing the IDAT payload")
  func readHeaderIsCheapAndIndependentOfPixelData() {
    let header = PNGDecoder.readHeader(Self.fixturePNGBytes)
    #expect(header?.width == 9)
    #expect(header?.height == 7)
    #expect(header?.colorType == 6)
    #expect(header?.interlaceMethod == 0)
  }

  @Test("Rejects a bad signature")
  func rejectsBadSignature() {
    let bytes: [UInt8] = Array("NOTAPNG".utf8) + [UInt8](repeating: 0, count: 40)
    #expect(PNGDecoder.decode(bytes) == nil)
    #expect(PNGDecoder.readHeader(bytes) == nil)
  }

  @Test("Rejects empty input")
  func rejectsEmptyInput() {
    #expect(PNGDecoder.decode([]) == nil)
  }

  @Test("Rejects truncated input")
  func rejectsTruncatedInput() {
    #expect(PNGDecoder.decode(Array(Self.fixturePNGBytes.prefix(60))) == nil)
  }

  @Test("Rejects 16-bit depth (v1 scope is 8-bit only)")
  func rejectsUnsupportedBitDepth() {
    // The header itself is well-formed, so `readHeader` succeeds...
    #expect(PNGDecoder.readHeader(Self.fixtureUnsupportedBitDepthPNG)?.bitDepth == 16)
    // ...but the full decode must refuse rather than misinterpret 16-bit
    // samples as 8-bit.
    #expect(PNGDecoder.decode(Self.fixtureUnsupportedBitDepthPNG) == nil)
  }

  @Test("Rejects palette color type (v1 scope is grayscale/RGB/RGBA only)")
  func rejectsUnsupportedColorType() {
    #expect(PNGDecoder.readHeader(Self.fixtureUnsupportedPaletteColorTypePNG)?.colorType == 3)
    #expect(PNGDecoder.decode(Self.fixtureUnsupportedPaletteColorTypePNG) == nil)
  }

  @Test("Rejects interlaced PNGs (v1 scope is non-interlaced only)")
  func rejectsInterlacedPNG() {
    #expect(PNGDecoder.readHeader(Self.fixtureUnsupportedInterlacePNG)?.interlaceMethod == 1)
    #expect(PNGDecoder.decode(Self.fixtureUnsupportedInterlacePNG) == nil)
  }
}
