import Foundation

/// Resolves the IBus daemon's PRIVATE bus address — this is NOT the D-Bus
/// session bus. IBus owns a session-bus name (`org.freedesktop.IBus`) but
/// only ever puts a stub object there; the real API (engine registration,
/// `Bus.CurrentInputContext`, per-context `CommitText`, etc.) lives on a
/// separate, private bus whose address has to be discovered first.
/// Verified on the target VM (GNOME Shell 46, IBus 1.5.29-rc2): `busctl
/// --user introspect org.freedesktop.IBus /org/freedesktop/IBus` returns
/// only a root object — confirming this resolution step is load-bearing,
/// not defensive.
///
/// Pure decision logic only — no socket I/O happens in this type. Both the
/// environment and file reads are injected (mirrors `SessionType.detect`
/// and `AccessibilityBusResolver`), so this is fully testable with fakes.
///
/// ## Resolution order
/// Mirrors `ibus_get_address()` in IBus's own `src/ibusshare.c`, verified
/// directly against two real tags/branches fetched from
/// `github.com/ibus/ibus`: `1.5.29-rc2` (the exact version installed on
/// the target VM per the POC) and current `master` — both implement it
/// identically:
///   1. The `IBUS_ADDRESS` environment variable, returned as-is if set and
///      non-empty (`ibus_get_address` returns it unconditionally the
///      moment `g_getenv` finds it, before touching the filesystem).
///   2. Otherwise, the socket-address file at `ibus_get_socket_path()`,
///      read line-by-line for a `KEY=value` line whose key is
///      `IBUS_ADDRESS`.
///
/// ## The disputed file path, resolved by reading the source
/// The brief for this task carried two candidate locations that disagreed:
///   - `$XDG_RUNTIME_DIR/ibus/bus/<hash>-unix-<display>`
///   - `~/.config/ibus/bus/<machine-id>-<hostname>-<display>`
///
/// `ibus_get_socket_path()` (both versions checked) resolves this: the
/// directory is `g_get_user_config_dir()` — i.e. `$XDG_CONFIG_HOME`,
/// defaulting to `~/.config` — never `$XDG_RUNTIME_DIR`. The function's
/// own comment says so explicitly: *"XDG_RUNTIME_DIR is not useful because
/// it's generated by login but not `su` command and ibus-daemon can be run
/// with `su`."* The filename is a literal `"%s-%s-%s"` sprintf of
/// `ibus_get_local_machine_id()`, a `hostname` token, and a
/// `displaynumber` token — never a cryptographic hash of anything, which
/// resolves the "hash" framing in the first candidate in favor of the
/// second's plain-concatenation description.
/// `ibus_get_local_machine_id()` reads `/var/lib/dbus/machine-id`, falling
/// back to `/etc/machine-id` (exactly as the brief described), and falls
/// back further to the literal string `"machine-id"` if both are
/// unreadable — modeled here too, so a machine with neither file still
/// resolves a (wrong but non-crashing) deterministic path rather than
/// aborting resolution.
///
/// The `hostname`/`displaynumber` tokens themselves come from
/// `WAYLAND_DISPLAY` (hostname fixed to `"unix"`, display number is the
/// whole value) or else `DISPLAY`, parsed as `[hostname]:display[.screen]`
/// (screen number dropped, empty hostname folds to `"unix"`) — matching
/// `ibus_get_socket_path`'s own parsing loop.
///
/// Given the source is unambiguous about the CURRENT real path, this type
/// checks `$XDG_CONFIG_HOME` (or its `~/.config` default) FIRST. It still
/// also checks the `$XDG_RUNTIME_DIR` variant as a second candidate, per
/// this task's explicit instruction to attempt both locations — cheap
/// insurance against a patched/older ibus build — but no version of
/// `ibusshare.c` inspected (`1.5.29-rc2` through `master`) actually reads
/// from there.
///
/// One deliberate simplification versus the real `ibus_get_address()`:
/// the C implementation also reads an `IBUS_DAEMON_PID=` line from the
/// same file and discards the address unless `kill(pid, 0)` proves that
/// PID is still alive — a real process-liveness check, which is out of
/// scope for this pure-logic module (no live process/socket code, per
/// this task's brief). This type reads only the `IBUS_ADDRESS=` line, so
/// it can return a stale address for a daemon that has since exited; the
/// caller that actually dials the address is expected to treat a failed
/// connection as "no IBus available," same as it must already do for a
/// wrong/garbage address.
/// Pairs a resolved address with the `IBUS_DAEMON_PID=` line from the SAME
/// socket file, for T-IBUS-PIDLIVE (`IBusAddressResolution`'s own doc
/// comment above: the real `ibus_get_address()` discards a file-sourced
/// address unless `kill(pid, 0)` proves that PID is still alive — a real
/// process-liveness syscall, deliberately out of scope for this pure-logic
/// module). See `IBusAddressResolution.resolveWithDaemonPID(environment:
/// readFile:)`'s doc comment for how this is produced.
public struct IBusResolvedAddress: Equatable, Sendable {
  public var address: String
  /// `nil` exactly when either (a) the address came from the `IBUS_ADDRESS`
  /// environment variable — upstream's own `ibus_get_address()` returns
  /// that unconditionally, before ever touching a PID or the filesystem,
  /// same as `resolve(environment:readFile:)`'s existing precedence — or
  /// (b) the socket file that DID supply the address had no parseable
  /// `IBUS_DAEMON_PID=` line. Either way, this module has no basis to gate
  /// the address on liveness; the connection layer (`IBusCommitClient`)
  /// degrades to trusting the address as-is, exactly the behavior every
  /// caller already had before T-IBUS-PIDLIVE existed.
  public var daemonPID: Int32?

  public init(address: String, daemonPID: Int32?) {
    self.address = address
    self.daemonPID = daemonPID
  }
}

public enum IBusAddressResolution {
  /// `ibus_get_socket_path()`'s literal fallback when both machine-id
  /// files are unreadable.
  private static let unknownMachineId = "machine-id"

  private static let addressKeyPrefix = "IBUS_ADDRESS="
  private static let daemonPIDKeyPrefix = "IBUS_DAEMON_PID="
  private static let commentLinePrefix = "#"

  /// Resolves the IBus private-bus address using `ibus_get_address()`'s
  /// own precedence. A thin wrapper over `resolveWithDaemonPID(environment:
  /// readFile:)` that drops the paired PID — kept as its own entry point
  /// because it predates T-IBUS-PIDLIVE and every existing call site/test
  /// only ever needed the address.
  ///
  /// - Parameters:
  ///   - environment: typically `ProcessInfo.processInfo.environment`.
  ///   - readFile: reads a file's full contents, returning `nil` if it
  ///     does not exist or cannot be read. Injected so this type never
  ///     touches the real filesystem itself — tests supply an in-memory
  ///     fake.
  /// - Returns: the resolved address, or `nil` if `IBUS_ADDRESS` is unset
  ///   and neither candidate socket-address file yields a usable
  ///   `IBUS_ADDRESS=` line. Never throws, never crashes — a missing,
  ///   empty, or garbage file degrades to `nil`.
  public static func resolve(
    environment: [String: String],
    readFile: (String) -> String?
  ) -> String? {
    resolveWithDaemonPID(environment: environment, readFile: readFile)?.address
  }

  /// Same resolution/precedence as `resolve(environment:readFile:)`, but
  /// also surfaces the `IBUS_DAEMON_PID=` line from whichever socket file
  /// actually supplied the address — see `IBusResolvedAddress.daemonPID`'s
  /// doc comment for exactly when that's `nil`. T-IBUS-PIDLIVE: still PURE
  /// — no `kill(pid, 0)` syscall happens here, this only PARSES a PID out
  /// of text this module already reads. The live-process liveness check
  /// itself belongs at the connection layer (`IBusCommitClient`, this
  /// function's one real caller), matching this file's own top-level doc
  /// comment on why that syscall was originally out of scope here.
  public static func resolveWithDaemonPID(
    environment: [String: String],
    readFile: (String) -> String?
  ) -> IBusResolvedAddress? {
    if let address = environment["IBUS_ADDRESS"], !address.isEmpty {
      return IBusResolvedAddress(address: address, daemonPID: nil)
    }
    for candidatePath in candidateSocketPaths(environment: environment, readFile: readFile) {
      guard let contents = readFile(candidatePath) else { continue }
      guard let address = parseAddress(fromSocketFileContents: contents) else { continue }
      return IBusResolvedAddress(
        address: address, daemonPID: parseDaemonPID(fromSocketFileContents: contents))
    }
    return nil
  }

  /// Both filesystem locations named in this task's brief for
  /// `ibus_get_socket_path()`'s result — see the type-level doc comment
  /// for which one the verified source actually implements (checked
  /// first) and why the other is still attempted.
  static func candidateSocketPaths(
    environment: [String: String],
    readFile: (String) -> String?
  ) -> [String] {
    let fileName = socketFileName(environment: environment, readFile: readFile)
    var paths: [String] = []
    if let configDir = userConfigDir(environment: environment) {
      paths.append("\(configDir)/ibus/bus/\(fileName)")
    }
    if let runtimeDir = environment["XDG_RUNTIME_DIR"], !runtimeDir.isEmpty {
      paths.append("\(runtimeDir)/ibus/bus/\(fileName)")
    }
    return paths
  }

  /// `g_get_user_config_dir()`: `$XDG_CONFIG_HOME` if set and non-empty,
  /// else `$HOME/.config`. `nil` only when neither is available.
  static func userConfigDir(environment: [String: String]) -> String? {
    if let configHome = environment["XDG_CONFIG_HOME"], !configHome.isEmpty {
      return configHome
    }
    if let home = environment["HOME"], !home.isEmpty {
      return "\(home)/.config"
    }
    return nil
  }

  /// The literal `"%s-%s-%s"` sprintf from `ibus_get_socket_path()`:
  /// machine id, hostname, display number.
  static func socketFileName(
    environment: [String: String],
    readFile: (String) -> String?
  ) -> String {
    let (hostname, displayNumber) = hostnameAndDisplayNumber(environment: environment)
    return "\(machineId(readFile: readFile))-\(hostname)-\(displayNumber)"
  }

  /// `ibus_get_local_machine_id()`: `/var/lib/dbus/machine-id`, falling
  /// back to `/etc/machine-id`, falling back to the literal string
  /// `"machine-id"` if neither is readable. Whichever file IS read wins
  /// outright (its trimmed contents are used even if empty) — this
  /// mirrors the C source exactly, which never falls through to the
  /// second path once the first `g_file_get_contents` call succeeds.
  static func machineId(readFile: (String) -> String?) -> String {
    if let contents = readFile("/var/lib/dbus/machine-id") {
      return contents.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    if let contents = readFile("/etc/machine-id") {
      return contents.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    return unknownMachineId
  }

  /// Mirrors `ibus_get_socket_path()`'s `WAYLAND_DISPLAY`/`DISPLAY`
  /// parsing. An empty `WAYLAND_DISPLAY`/`DISPLAY` is treated as unset
  /// (matches this module's existing convention in `SessionType.detect`)
  /// rather than the C source's pointer-truthy check, which would let a
  /// literal empty string through — a deliberately narrow deviation for
  /// robustness, since an empty display value degenerating into an empty
  /// path segment serves nobody.
  static func hostnameAndDisplayNumber(environment: [String: String]) -> (
    hostname: String, displayNumber: String
  ) {
    if let waylandDisplay = environment["WAYLAND_DISPLAY"], !waylandDisplay.isEmpty {
      return ("unix", waylandDisplay)
    }
    guard let display = environment["DISPLAY"], !display.isEmpty else {
      return ("unix", "0")
    }
    // DISPLAY's grammar is `[hostname]:displaynumber[.screennumber]`.
    guard let colonIndex = display.firstIndex(of: ":") else {
      return (display, "0")
    }
    let hostnamePart = String(display[display.startIndex..<colonIndex])
    let afterColon = display[display.index(after: colonIndex)...]
    let displayNumberPart = afterColon.firstIndex(of: ".").map { afterColon[..<$0] } ?? afterColon
    let hostname = hostnamePart.isEmpty ? "unix" : hostnamePart
    let displayNumber = displayNumberPart.isEmpty ? "0" : String(displayNumberPart)
    return (hostname, displayNumber)
  }

  /// Parses `KEY=value` lines for the last `IBUS_ADDRESS=` line (matching
  /// `ibus_write_address()`'s own single-`IBUS_ADDRESS=`-line format,
  /// while tolerating a hypothetical repeat the same way the C reader
  /// does — by letting the later line win) — `#`-prefixed comment lines
  /// are skipped. Returns `nil` on empty, malformed, or comment-only
  /// content: never crashes.
  static func parseAddress(fromSocketFileContents contents: String) -> String? {
    var address: String?
    for rawLine in contents.split(separator: "\n", omittingEmptySubsequences: false) {
      let line = rawLine.trimmingCharacters(in: .init(charactersIn: "\r"))
      if line.hasPrefix(commentLinePrefix) { continue }
      guard line.hasPrefix(addressKeyPrefix) else { continue }
      address = String(line.dropFirst(addressKeyPrefix.count))
    }
    guard let address, !address.isEmpty else { return nil }
    return address
  }

  /// Parses the `IBUS_DAEMON_PID=` line the SAME socket file
  /// `parseAddress(fromSocketFileContents:)` reads carries — verbatim from
  /// `ibus_get_address()` (`src/ibusshare.c`): both lines are written by
  /// the same `ibus_write_address()` call into the same file. Same
  /// contract as `parseAddress`: `#`-comments skipped, the LAST matching
  /// line wins, and anything empty/missing/non-numeric degrades to `nil`
  /// rather than crashing (`Int32.init?(_:)` already returns `nil` on a
  /// non-numeric string, so a garbage value is handled for free).
  static func parseDaemonPID(fromSocketFileContents contents: String) -> Int32? {
    var pid: Int32?
    for rawLine in contents.split(separator: "\n", omittingEmptySubsequences: false) {
      let line = rawLine.trimmingCharacters(in: .init(charactersIn: "\r"))
      if line.hasPrefix(commentLinePrefix) { continue }
      guard line.hasPrefix(daemonPIDKeyPrefix) else { continue }
      pid = Int32(line.dropFirst(daemonPIDKeyPrefix.count))
    }
    return pid
  }
}
